import { User, Category, Transaction, Account } from '@/types/financial';

export const mockUser: User = {
  id: '1',
  name: 'John Doe',
  email: 'john.doe@example.com',
  avatar: 'https://ui-avatars.com/api/?name=John+Doe',
  createdAt: new Date(),
};

export const mockCategories: Category[] = [
  {
    id: '1',
    name: 'Alimentação',
    icon: 'utensils',
    color: '#EF4444',
    type: 'expense',
    budgetLimit: 500,
  },
  {
    id: '2',
    name: 'Transporte',
    icon: 'bus',
    color: '#F59E0B',
    type: 'expense',
    budgetLimit: 300,
  },
  {
    id: '3',
    name: 'Moradia',
    icon: 'home',
    color: '#3B82F6',
    type: 'expense',
    budgetLimit: 1200,
  },
  {
    id: '4',
    name: 'Salário',
    icon: 'dollar-sign',
    color: '#10B981',
    type: 'income',
  },
  {
    id: '5',
    name: 'Freelance',
    icon: 'code',
    color: '#6366F1',
    type: 'income',
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: '1',
    amount: 50,
    description: 'Almoço no restaurante',
    date: new Date(),
    type: 'expense',
    categoryId: '1',
    accountId: '1',
    userId: '1',
  },
  {
    id: '2',
    amount: 30,
    description: 'Uber para o trabalho',
    date: new Date(),
    type: 'expense',
    categoryId: '2',
    accountId: '1',
    userId: '1',
  },
  {
    id: '3',
    amount: 1200,
    description: 'Aluguel do apartamento',
    date: new Date(),
    type: 'expense',
    categoryId: '3',
    accountId: '1',
    userId: '1',
  },
  {
    id: '4',
    amount: 3000,
    description: 'Salário mensal',
    date: new Date(),
    type: 'income',
    categoryId: '4',
    accountId: '1',
    userId: '1',
  },
  {
    id: '5',
    amount: 500,
    description: 'Projeto de desenvolvimento web',
    date: new Date(),
    type: 'income',
    categoryId: '5',
    accountId: '1',
    userId: '1',
  },
  {
    id: '6',
    amount: 75,
    description: 'Jantar com amigos',
    date: new Date('2024-07-03'),
    type: 'expense',
    categoryId: '1',
    accountId: '1',
    userId: '1',
  },
  {
    id: '7',
    amount: 25,
    description: 'Passagem de ônibus',
    date: new Date('2024-07-03'),
    type: 'expense',
    categoryId: '2',
    accountId: '1',
    userId: '1',
  },
  {
    id: '8',
    amount: 1200,
    description: 'Aluguel',
    date: new Date('2024-07-05'),
    type: 'expense',
    categoryId: '3',
    accountId: '1',
    userId: '1',
  },
  {
    id: '9',
    amount: 3000,
    description: 'Salário',
    date: new Date('2024-07-10'),
    type: 'income',
    categoryId: '4',
    accountId: '1',
    userId: '1',
  },
  {
    id: '10',
    amount: 500,
    description: 'Freelance Project',
    date: new Date('2024-07-15'),
    type: 'income',
    categoryId: '5',
    accountId: '1',
    userId: '1',
  },
  {
    id: '11',
    amount: 60,
    description: 'Supermercado',
    date: new Date('2024-07-17'),
    type: 'expense',
    categoryId: '1',
    accountId: '1',
    userId: '1',
  },
  {
    id: '12',
    amount: 40,
    description: 'Combustível',
    date: new Date('2024-07-20'),
    type: 'expense',
    categoryId: '2',
    accountId: '1',
    userId: '1',
  },
  {
    id: '13',
    amount: 1200,
    description: 'Aluguel',
    date: new Date('2024-08-05'),
    type: 'expense',
    categoryId: '3',
    accountId: '1',
    userId: '1',
  },
  {
    id: '14',
    amount: 3000,
    description: 'Salário',
    date: new Date('2024-08-10'),
    type: 'income',
    categoryId: '4',
    accountId: '1',
    userId: '1',
  },
  {
    id: '15',
    amount: 500,
    description: 'Freelance Project',
    date: new Date('2024-08-15'),
    type: 'income',
    categoryId: '5',
    accountId: '1',
    userId: '1',
  },
];

export const mockAccounts: Account[] = [
  {
    id: '1',
    name: 'Conta Corrente Banco do Brasil',
    type: 'checking',
    balance: 2500.00,
    userId: '1',
    color: '#3B82F6',
    icon: 'Building'
  },
  {
    id: '2',
    name: 'Poupança Caixa',
    type: 'savings',
    balance: 15000.00,
    userId: '1',
    color: '#10B981',
    icon: 'PiggyBank'
  },
  {
    id: '3',
    name: 'Cartão Nubank',
    type: 'credit',
    balance: -850.00,
    userId: '1',
    color: '#8B5CF6',
    icon: 'CreditCard'
  },
  {
    id: '4',
    name: 'Carteira',
    type: 'wallet',
    balance: 150.00,
    userId: '1',
    color: '#F59E0B',
    icon: 'Wallet'
  }
];
