// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tuxtnuewaifeqvuwujuj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1eHRudWV3YWlmZXF2dXd1anVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MzcwNTIsImV4cCI6MjA2MzQxMzA1Mn0.3jmv8LEjnWefDaEJLVDLhPR0Zt6ljDiWcMXx-2swNG0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);